### ISSUE TITLE
#001 - Arquitetura de Software

### ISSUE THREAD

**Issue by phmiranda** [cpa-bayarea/Prontuario-eletronico#10]
- [ ] Arquitetura baseada em módulos (Zend Framework 2.5)
- [ ] Instalação do framework twitter bootstrap na sua versão: 3.3.7
- [ ] Instalação da biblioteca jquery na sua versão 3.3.1

**Comment by dougs007** [comment]
@phmiranda O Ítalo falou que não trabalharemos com a arquitetura baseada em módulos (''Arquitetura padrão do framework'') ... O que seria esse 2º tópico ?

**Comment by phmiranda** [comment]
@dougs007 isso para lembrar o tópico mesmo, eu vou alterar esses itens esse final de semana.assim que finalizar a estruturação eu vou commitar e você mostra.
